Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9" 
  config.vm.hostname = "rocky9"

  config.vm.network "private_network", ip: "192.168.56.20"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "step1-rocky9"
    vb.memory = 1024
    vb.cpus    = 1
  end
end
