apiVersion: v1
kind: Pod
metadata:
  name: secret-envvar-pod
spec:
  containers:
    - name: secret-container
      image: alpine
      command: ["sleep", "3600"]
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: user-pass-nuovo
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-pass-nuovo
              key: password
