apiVersion: v1
data:
  password: YWRtaW40NTY=
  username: cGFwZXJpbm8=
kind: Secret
metadata:
  creationTimestamp: "2026-07-07T09:48:20Z"
  name: user-pass-nuovo
  namespace: default
  resourceVersion: "2983"
  uid: c5f0577e-0d1f-4f8c-bd5a-0788acea3a31
type: Opaque
