Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"
  config.vm.hostname = "rocky99"
  config.vm.network "private_network", ip: "192.168.56.30"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "rocky98"
    vb.memory = 1024
    vb.cpus   = 1
  end
end

