Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"
  config.vm.hostname = "jinja-lab"

  config.vm.network "private_network", ip: "192.168.56.40"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "jinja-lab-rocky9"
    vb.memory = "1024"
    vb.cpus   = 1
  end
end
